# Uncomment the next line to define a global platform for your project
# platform :ios, '15.0'

target 'Sunsijo-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sunsijo-iOS
pod 'SnapKit'
pod 'Then'
pod 'Alamofire'
pod 'RxSwift'
pod 'RxCocoa'
pod 'RxFlow'
pod 'SwiftLint'
pod 'DLRadioButton'

end
